This is makeindex, version 2.16 [MiKTeX 23.10].
Scanning style file ./thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (15 entries accepted, 0 rejected).
Sorting entries....done (65 comparisons).
Generating output file thesis.acr....done (26 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
