This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (13 entries accepted, 0 rejected).
Sorting entries....done (52 comparisons).
Generating output file thesis.acr....done (25 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
